# Generated by Django 4.1.7 on 2023-05-01 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 5, 1, 13, 16, 14, 443947), verbose_name='Опубликована'),
        ),
    ]
